/**
 * Well-known Moroccan cities for CRM forms (orders, clients, etc.).
 * Sorted alphabetically (fr), with local Agadir-area towns included.
 * Keep "Autre" as a separate option in the UI when needed.
 */
export const MOROCCO_CITIES = [
  "Agadir",
  "Aïn Harrouda",
  "Aïn Taoujdate",
  "Al Hoceima",
  "Aourir",
  "Asilah",
  "Azemmour",
  "Azilal",
  "Azrou",
  "Aït Melloul",
  "Beni Mellal",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Biougra",
  "Boujdour",
  "Boulemane",
  "Bouznika",
  "Casablanca",
  "Chefchaouen",
  "Chichaoua",
  "Dakhla",
  "Dcheira",
  "El Hajeb",
  "El Jadida",
  "El Kelaa des Sraghna",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Figuig",
  "Fnideq",
  "Fquih Ben Salah",
  "Guelmim",
  "Guercif",
  "Ifrane",
  "Inezgane",
  "Jerada",
  "Kénitra",
  "Khemisset",
  "Khénifra",
  "Khouribga",
  "Ksar El Kebir",
  "Laâyoune",
  "Larache",
  "Marrakech",
  "Martil",
  "Médiouna",
  "Meknès",
  "Midelt",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Ouazzane",
  "Oued Zem",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirat",
  "Smara",
  "Souk El Arbaa",
  "Tanger",
  "Tan-Tan",
  "Taounate",
  "Taourirt",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
  "Tifelt",
  "Tinghir",
  "Tiznit",
  "Youssoufia",
  "Zagora",
] as const;

export type MoroccoCity = (typeof MOROCCO_CITIES)[number];

/** Options for Select components, ending with "Autre". */
export const MOROCCO_CITY_OPTIONS = [
  ...MOROCCO_CITIES.map((city) => ({ value: city, label: city })),
  { value: "Autre", label: "Autre" },
] as const;
